name: bmorel-pi-blog
services:
  server:
    image: hugomods/hugo:exts-non-root
    command: server -D --poll 700ms
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
  deploy:
    build:
      context: .
    environment:
      HUGO_BASEURL: "http://localhost:8080"
    ports:
      - "8080:80"