apiVersion: v1
kind: Service
metadata:
  name: blog-server-service
spec:
  selector:
    app: blog-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31500
  type: NodePort